sudo: required
os:
  - linux
language: python
python:
  - 3.6
env:
  - TEST_SUITE=scripts/travis_test_4.sh
  - TEST_SUITE=scripts/travis_test_5.sh
  - TEST_SUITE=scripts/travis_test_upgradability.sh
  - TEST_SUITE=scripts/travis_test_data_dependency.sh
  - TEST_SUITE=scripts/travis_test_find_paths.sh
  - TEST_SUITE=scripts/travis_test_truffle.sh
  - TEST_SUITE=scripts/travis_test_embark.sh
  - TEST_SUITE=scripts/travis_test_etherscan.sh
  - TEST_SUITE=scripts/travis_test_dapp.sh
  - TEST_SUITE=scripts/travis_test_etherlime.sh
  - TEST_SUITE=scripts/travis_test_cli.sh
  - TEST_SUITE=scripts/travis_test_printers.sh
  - TEST_SUITE=scripts/travis_test_slither_config.sh
  - TEST_SUITE=scripts/travis_test_simil.sh
  - TEST_SUITE=scripts/travis_test_erc.sh
  - TEST_SUITE=scripts/travis_test_kspec.sh
branches:
  only:
  - master
  - dev

install:
  - scripts/travis_install.sh

script:
  - $TEST_SUITE



