---
name: Doctor

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'slither/tools/doctor/**'
      - '.github/workflows/doctor.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  slither-doctor:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-2022"]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        exclude:
          # strange failure
          - os: windows-2022
            python: 3.8
    steps:
      - uses: actions/checkout@v6

      - name: Install uv and Python ${{ matrix.python }}
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python }}

      - name: Try system-wide Slither
        run: |
          echo "::group::Install slither"
          uv pip install --system .
          echo "::endgroup::"

          # escape cwd so python doesn't pick up local module
          cd /

          echo "::group::Via module"
          python3 -m slither.tools.doctor .
          echo "::endgroup::"

          echo "::group::Via binary"
          slither-doctor .
          echo "::endgroup::"

      - name: Try venv Slither
        run: |
          echo "::group::Install slither"
          uv venv venv
          source venv/bin/activate || source venv/Scripts/activate
          hash -r
          uv pip install .
          echo "::endgroup::"

          # escape cwd so python doesn't pick up local module
          cd /

          echo "::group::Via module"
          python3 -m slither.tools.doctor .
          echo "::endgroup::"

          echo "::group::Via binary"
          slither-doctor .
          echo "::endgroup::"
