---
name: Doctor

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'slither/tools/doctor/**'
      - '.github/workflows/doctor.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  slither-doctor:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-2025"]
        python: ["3.9", "3.14"]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6
        with:
          persist-credentials: false

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  # v6
        with:
          python-version: ${{ matrix.python }}

      - name: Install uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b  # v7
        with:
          enable-cache: true

      - name: Try system-wide Slither
        run: |
          echo "::group::Install slither"
          uv pip install --system .
          echo "::endgroup::"

          # escape cwd so python doesn't pick up local module
          cd /

          echo "::group::Via module"
          python3 -m slither.tools.doctor "$GITHUB_WORKSPACE"
          echo "::endgroup::"

          echo "::group::Via binary"
          slither-doctor "$GITHUB_WORKSPACE"
          echo "::endgroup::"

      - name: Try venv Slither
        run: |
          echo "::group::Install slither"
          uv venv
          uv pip install .
          source .venv/bin/activate || source .venv/Scripts/activate
          hash -r
          echo "::endgroup::"

          # escape cwd so python doesn't pick up local module
          cd /

          echo "::group::Via module"
          python3 -m slither.tools.doctor "$GITHUB_WORKSPACE"
          echo "::endgroup::"

          echo "::group::Via binary"
          slither-doctor "$GITHUB_WORKSPACE"
          echo "::endgroup::"
