---
name: Lint Code Base

defaults:
  run:
    # To load bashrc
    shell: bash -ieo pipefail {0}

on:
  pull_request:
    branches: [master, dev]
    
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron: '0 12 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Superlinter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          mkdir -p .github/linters
          cp pyproject.toml .github/linters

      - name: Register yamllint problem matcher
        run: |
          echo "::add-matcher::.github/workflows/matchers/yamllint.json"

      - name: Lint everything else
        uses: super-linter/super-linter/slim@v6.1.1
        if: always()
        env:
          # run linter on everything to catch preexisting problems
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Always false
          VALIDATE_PYTHON: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_JSON: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_JSCPD: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_CHECKOV: false
          # TODO: consider enabling
          VALIDATE_SHELL_SHFMT: false
          SHELLCHECK_OPTS: "-e SC1090"
          FILTER_REGEX_EXCLUDE: .*tests/.*.(json|zip|sol)
