---
name: Parser tests

defaults:
  run:
    # To load bashrc
    shell: bash -ieo pipefail {0}

on:
  push:
    branches:
      - patch-1
  pull_request:
    branches: [master, dev]
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron: '0 12 * * *'

jobs:
  build:
    name: Parser tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2022]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v3
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |

          python setup.py install
          pip install deepdiff
          pip install pytest==7.0.1
          pip install typing_extensions==4.1.1
          pip install importlib_metadata==4.8.3
          pip install "solc-select>=v1.0.0b1"

      - name: Install solc
        run: |
          solc-select install all
          solc-select use 0.8.0

      - name: Test with pytest
        run: |
          pytest tests/test_ast_parsing.py
          pytest tests/test_path_filtering/test_path_filtering.py
